name: Buduj AAPS Prosto

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pobieranie kodu
        uses: actions/checkout@v4

      - name: Ustawienie Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Przygotowanie klucza
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > keystore.jks

      - name: Nadanie uprawnien gradlew
        run: chmod +x gradlew

      - name: Kompilacja APK
        run: ./gradlew :app:assembleFullRelease --no-daemon -x verifyFullReleaseResources

      - name: Podpisanie APK
        run: |
          APK_RAW=$(find app/build/outputs/apk/ -name "*.apk" | head -n 1)
          $ANDROID_HOME/build-tools/34.0.0/zipalign -v -p 4 "$APK_RAW" aligned.apk || cp "$APK_RAW" aligned.apk
          $ANDROID_HOME/build-tools/34.0.0/apksigner sign --ks keystore.jks --ks-pass "pass:${{ secrets.KEYSTORE_PASSWORD }}" --ks-key-alias "${{ secrets.KEY_ALIAS }}" --key-pass "pass:${{ secrets.KEY_PASSWORD }}" --out AndroidAPS-Gotowy.apk aligned.apk

      - name: Zapisanie APK
        uses: actions/upload-artifact@v4
        with:
          name: AndroidAPS-Gotowa-Aplikacja
          path: AndroidAPS-Gotowy.apk
