name: Buduj AAPS Prosto

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pobieranie kodu
        uses: actions/checkout@v4

      - name: Ustawienie Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Przygotowanie klucza
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > keystore.jks
          echo "keyStore.file=../keystore.jks" > keystore.properties
          echo "keyStore.password=${{ secrets.KEYSTORE_PASSWORD }}" >> keystore.properties
          echo "keyStore.keyAlias=${{ secrets.KEY_ALIAS }}" >> keystore.properties
          echo "keyStore.keyPassword=${{ secrets.KEY_PASSWORD }}" >> keystore.properties
          echo "storeFile=../keystore.jks" >> keystore.properties
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> keystore.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> keystore.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> keystore.properties
          cp keystore.properties app/keystore.properties
          cp keystore.jks app/keystore.jks

      - name: Nadanie uprawnien gradlew
        run: chmod +x gradlew

      - name: Kompilacja APK
        run: ./gradlew assembleFullRelease --no-daemon

      - name: Zapisanie gotowej aplikacji APK
        uses: actions/upload-artifact@v4
        with:
          name: AndroidAPS-Gotowa-Aplikacja
          path: app/build/outputs/apk/**/*.apk
